"""Catalogo de tickers y exchange en watchlist

Revision ID: 8f91a9a270b4
Revises: 62621dce6840
Create Date: 2026-08-04 14:26:44.554937

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f91a9a270b4"
down_revision: str | Sequence[str] | None = "62621dce6840"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickers",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("primary_exchange", sa.String(length=20), nullable=True),
        sa.Column(
            "exchange",
            sa.Enum(
                "NASDAQ",
                "NYSE",
                "OTHER",
                name="exchangetype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("asset_type", sa.String(length=16), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_index(op.f("ix_tickers_exchange"), "tickers", ["exchange"], unique=False)
    op.add_column(
        "watchlists",
        sa.Column(
            "exchange",
            sa.Enum(
                "NASDAQ",
                "NYSE",
                "OTHER",
                name="exchangetype",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("watchlists", "exchange")
    op.drop_index(op.f("ix_tickers_exchange"), table_name="tickers")
    op.drop_table("tickers")
    # ### end Alembic commands ###
